// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitcoinlightclient/btclightclient/btc_header.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Btcheader struct {
}

func (m *Btcheader) Reset()         { *m = Btcheader{} }
func (m *Btcheader) String() string { return proto.CompactTextString(m) }
func (*Btcheader) ProtoMessage()    {}
func (*Btcheader) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4b8f74d42ccc907, []int{0}
}
func (m *Btcheader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Btcheader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Btcheader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Btcheader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Btcheader.Merge(m, src)
}
func (m *Btcheader) XXX_Size() int {
	return m.Size()
}
func (m *Btcheader) XXX_DiscardUnknown() {
	xxx_messageInfo_Btcheader.DiscardUnknown(m)
}

var xxx_messageInfo_Btcheader proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Btcheader)(nil), "bitcoinlightclient.btclightclient.Btcheader")
}

func init() {
	proto.RegisterFile("bitcoinlightclient/btclightclient/btc_header.proto", fileDescriptor_d4b8f74d42ccc907)
}

var fileDescriptor_d4b8f74d42ccc907 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xca, 0x2c, 0x49,
	0xce, 0xcf, 0xcc, 0xcb, 0xc9, 0x4c, 0xcf, 0x28, 0x49, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x4f,
	0x02, 0x31, 0x50, 0xb8, 0xf1, 0x19, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x8a, 0x98, 0x7a, 0xf4, 0x50, 0xf5, 0x28, 0x71, 0x73, 0x71, 0x3a, 0x95, 0x24, 0x43,
	0x74, 0x39, 0xb9, 0x9c, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c,
	0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x16, 0xd4,
	0x24, 0x5d, 0x64, 0xfb, 0x2a, 0xd0, 0x1d, 0x50, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0xb6,
	0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x18, 0xe2, 0xe1, 0xb2, 0x00, 0x00, 0x00,
}

func (m *Btcheader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Btcheader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Btcheader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintBtcHeader(dAtA []byte, offset int, v uint64) int {
	offset -= sovBtcHeader(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Btcheader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovBtcHeader(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBtcHeader(x uint64) (n int) {
	return sovBtcHeader(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Btcheader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBtcHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Btcheader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Btcheader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipBtcHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBtcHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBtcHeader(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBtcHeader
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBtcHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBtcHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBtcHeader
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBtcHeader
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBtcHeader
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBtcHeader        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBtcHeader          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBtcHeader = fmt.Errorf("proto: unexpected end of group")
)
