// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitcoinlightclient/btclightclient/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b08c1df8dc8d70, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b08c1df8dc8d70, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetHeaderRequest struct {
	Height string `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryGetHeaderRequest) Reset()         { *m = QueryGetHeaderRequest{} }
func (m *QueryGetHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetHeaderRequest) ProtoMessage()    {}
func (*QueryGetHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b08c1df8dc8d70, []int{2}
}
func (m *QueryGetHeaderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHeaderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHeaderRequest.Merge(m, src)
}
func (m *QueryGetHeaderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHeaderRequest proto.InternalMessageInfo

func (m *QueryGetHeaderRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

type QueryGetHeaderResponse struct {
	Btcheader string `protobuf:"bytes,1,opt,name=btcheader,proto3" json:"btcheader,omitempty"`
}

func (m *QueryGetHeaderResponse) Reset()         { *m = QueryGetHeaderResponse{} }
func (m *QueryGetHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetHeaderResponse) ProtoMessage()    {}
func (*QueryGetHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b08c1df8dc8d70, []int{3}
}
func (m *QueryGetHeaderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHeaderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHeaderResponse.Merge(m, src)
}
func (m *QueryGetHeaderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHeaderResponse proto.InternalMessageInfo

func (m *QueryGetHeaderResponse) GetBtcheader() string {
	if m != nil {
		return m.Btcheader
	}
	return ""
}

type QueryLatestBlockRequest struct {
}

func (m *QueryLatestBlockRequest) Reset()         { *m = QueryLatestBlockRequest{} }
func (m *QueryLatestBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestBlockRequest) ProtoMessage()    {}
func (*QueryLatestBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b08c1df8dc8d70, []int{4}
}
func (m *QueryLatestBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestBlockRequest.Merge(m, src)
}
func (m *QueryLatestBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestBlockRequest proto.InternalMessageInfo

type QueryLatestBlockResponse struct {
	Btclightblock *BTCLightBlock `protobuf:"bytes,1,opt,name=btclightblock,proto3,customtype=BTCLightBlock" json:"btclightblock,omitempty"`
}

func (m *QueryLatestBlockResponse) Reset()         { *m = QueryLatestBlockResponse{} }
func (m *QueryLatestBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestBlockResponse) ProtoMessage()    {}
func (*QueryLatestBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b08c1df8dc8d70, []int{5}
}
func (m *QueryLatestBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestBlockResponse.Merge(m, src)
}
func (m *QueryLatestBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestBlockResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "bitcoinlightclient.btclightclient.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "bitcoinlightclient.btclightclient.QueryParamsResponse")
	proto.RegisterType((*QueryGetHeaderRequest)(nil), "bitcoinlightclient.btclightclient.QueryGetHeaderRequest")
	proto.RegisterType((*QueryGetHeaderResponse)(nil), "bitcoinlightclient.btclightclient.QueryGetHeaderResponse")
	proto.RegisterType((*QueryLatestBlockRequest)(nil), "bitcoinlightclient.btclightclient.QueryLatestBlockRequest")
	proto.RegisterType((*QueryLatestBlockResponse)(nil), "bitcoinlightclient.btclightclient.QueryLatestBlockResponse")
}

func init() {
	proto.RegisterFile("bitcoinlightclient/btclightclient/query.proto", fileDescriptor_27b08c1df8dc8d70)
}

var fileDescriptor_27b08c1df8dc8d70 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0xdf, 0x11, 0x0d, 0x64, 0x6a, 0x0f, 0x1d, 0x6b, 0xad, 0xa1, 0xa4, 0x9a, 0x93, 0x06, 0x9b,
	0xb1, 0x11, 0xfb, 0x47, 0x0f, 0x42, 0x14, 0xf4, 0xb0, 0x07, 0x5d, 0x3d, 0x79, 0x29, 0x93, 0x38,
	0x64, 0x07, 0xb3, 0x33, 0x69, 0x66, 0x2a, 0x16, 0xf1, 0xe2, 0x27, 0x10, 0xfc, 0x12, 0x82, 0x17,
	0x3f, 0x80, 0x07, 0xbd, 0xf5, 0x58, 0xf0, 0x22, 0x1e, 0x8a, 0xec, 0x0a, 0x7e, 0x0d, 0xc9, 0xcc,
	0xd4, 0xba, 0x1b, 0x61, 0xe3, 0x5e, 0xc2, 0x9b, 0xf7, 0xde, 0xef, 0xf7, 0x7e, 0xef, 0x4f, 0xe0,
	0x5a, 0xca, 0x54, 0x26, 0x18, 0x2f, 0x58, 0xde, 0x57, 0x59, 0xc1, 0x28, 0x57, 0x38, 0xad, 0x8d,
	0x93, 0xe7, 0xee, 0x1e, 0xad, 0xf6, 0xa3, 0xb2, 0x12, 0x4a, 0xa0, 0xcb, 0xcd, 0xf4, 0x68, 0x3c,
	0xdd, 0x5b, 0x20, 0x03, 0xc6, 0x05, 0xd6, 0x5f, 0x83, 0xf2, 0x16, 0x73, 0x91, 0x0b, 0x6d, 0xe2,
	0xda, 0xb2, 0xde, 0x95, 0x5c, 0x88, 0xbc, 0xa0, 0x98, 0x94, 0x0c, 0x13, 0xce, 0x85, 0x22, 0x8a,
	0x09, 0x2e, 0x6d, 0x34, 0xcc, 0x84, 0x1c, 0x08, 0x89, 0x53, 0x22, 0xa9, 0x91, 0x80, 0x5f, 0xac,
	0xa7, 0x54, 0x91, 0x75, 0x5c, 0x92, 0x9c, 0x71, 0x9d, 0x6c, 0x73, 0xa3, 0xe9, 0x4d, 0x94, 0xa4,
	0x22, 0x03, 0xcb, 0x1d, 0x2c, 0x42, 0xf4, 0xa8, 0x66, 0x7c, 0xa8, 0x9d, 0x3d, 0xba, 0xbb, 0x47,
	0xa5, 0x0a, 0x32, 0x78, 0x6e, 0xcc, 0x2b, 0x4b, 0xc1, 0x25, 0x45, 0x5d, 0xe8, 0x18, 0xf0, 0x32,
	0xb8, 0x04, 0xae, 0xcc, 0xc5, 0x57, 0xa3, 0xa9, 0x33, 0x88, 0x0c, 0x45, 0xe2, 0x1e, 0x1c, 0xad,
	0x76, 0xde, 0xff, 0xfa, 0x18, 0x82, 0x9e, 0xe5, 0x08, 0x30, 0x3c, 0xaf, 0x8b, 0xdc, 0xa7, 0xea,
	0x01, 0x25, 0xcf, 0x68, 0x65, 0xab, 0xa3, 0x25, 0xe8, 0xf4, 0x69, 0x4d, 0xa1, 0xcb, 0xb8, 0x3d,
	0xfb, 0x0a, 0x36, 0xe0, 0xd2, 0x24, 0xc0, 0x0a, 0x5b, 0x81, 0x6e, 0xaa, 0xb2, 0xbe, 0x76, 0x5a,
	0xd0, 0x89, 0x23, 0xb8, 0x08, 0x2f, 0x68, 0x5c, 0x97, 0x28, 0x2a, 0x55, 0x52, 0x88, 0xec, 0xf9,
	0x71, 0xa3, 0x8f, 0xe1, 0x72, 0x33, 0x64, 0x49, 0x37, 0xe1, 0xfc, 0x71, 0x2f, 0x69, 0x1d, 0xd0,
	0xc4, 0x67, 0x93, 0x85, 0xef, 0x47, 0xab, 0xf3, 0xc9, 0x93, 0xbb, 0xdd, 0x3a, 0x60, 0x10, 0xe3,
	0x79, 0xf1, 0xa7, 0xd3, 0xf0, 0x8c, 0x66, 0x45, 0x1f, 0x00, 0x74, 0xcc, 0x00, 0xd0, 0xcd, 0x16,
	0xb3, 0x6a, 0x6e, 0xc2, 0xdb, 0xf8, 0x5f, 0x98, 0x11, 0x1f, 0xc4, 0x6f, 0xbe, 0xfe, 0x7c, 0x77,
	0xea, 0x1a, 0x0a, 0xb1, 0xc5, 0xaf, 0x4d, 0xbd, 0x08, 0xf4, 0x05, 0x40, 0xf7, 0xcf, 0x6c, 0xd1,
	0x56, 0xdb, 0xca, 0x93, 0xfb, 0xf3, 0xb6, 0x67, 0x40, 0x5a, 0xd9, 0x77, 0xb4, 0xec, 0x6d, 0xb4,
	0xd9, 0x46, 0x76, 0x4e, 0xd5, 0x8e, 0x59, 0x31, 0x7e, 0x65, 0x4e, 0xe4, 0x35, 0xfa, 0x0c, 0xe0,
	0xdc, 0x5f, 0xcb, 0x44, 0xb7, 0xda, 0x6a, 0x69, 0x1e, 0x87, 0x77, 0x7b, 0x26, 0xac, 0xed, 0x64,
	0x4b, 0x77, 0x12, 0xa3, 0xeb, 0x6d, 0x3a, 0x29, 0x34, 0xc1, 0x8e, 0x3e, 0x9f, 0xe4, 0xde, 0xc1,
	0xd0, 0x07, 0x87, 0x43, 0x1f, 0xfc, 0x18, 0xfa, 0xe0, 0xed, 0xc8, 0xef, 0x1c, 0x8e, 0xfc, 0xce,
	0xb7, 0x91, 0xdf, 0x79, 0x1a, 0xfe, 0x8b, 0xea, 0xe5, 0x24, 0x99, 0xda, 0x2f, 0xa9, 0x4c, 0x1d,
	0xfd, 0x7f, 0xdf, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x7e, 0xd1, 0x37, 0xd6, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetHeader items.
	GetHeader(ctx context.Context, in *QueryGetHeaderRequest, opts ...grpc.CallOption) (*QueryGetHeaderResponse, error)
	// Queries a list of LatestBlock items.
	LatestBlock(ctx context.Context, in *QueryLatestBlockRequest, opts ...grpc.CallOption) (*QueryLatestBlockResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/bitcoinlightclient.btclightclient.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetHeader(ctx context.Context, in *QueryGetHeaderRequest, opts ...grpc.CallOption) (*QueryGetHeaderResponse, error) {
	out := new(QueryGetHeaderResponse)
	err := c.cc.Invoke(ctx, "/bitcoinlightclient.btclightclient.Query/GetHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestBlock(ctx context.Context, in *QueryLatestBlockRequest, opts ...grpc.CallOption) (*QueryLatestBlockResponse, error) {
	out := new(QueryLatestBlockResponse)
	err := c.cc.Invoke(ctx, "/bitcoinlightclient.btclightclient.Query/LatestBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetHeader items.
	GetHeader(context.Context, *QueryGetHeaderRequest) (*QueryGetHeaderResponse, error)
	// Queries a list of LatestBlock items.
	LatestBlock(context.Context, *QueryLatestBlockRequest) (*QueryLatestBlockResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetHeader(ctx context.Context, req *QueryGetHeaderRequest) (*QueryGetHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHeader not implemented")
}
func (*UnimplementedQueryServer) LatestBlock(ctx context.Context, req *QueryLatestBlockRequest) (*QueryLatestBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestBlock not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcoinlightclient.btclightclient.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcoinlightclient.btclightclient.Query/GetHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetHeader(ctx, req.(*QueryGetHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcoinlightclient.btclightclient.Query/LatestBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestBlock(ctx, req.(*QueryLatestBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bitcoinlightclient.btclightclient.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetHeader",
			Handler:    _Query_GetHeader_Handler,
		},
		{
			MethodName: "LatestBlock",
			Handler:    _Query_LatestBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitcoinlightclient/btclightclient/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetHeaderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHeaderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHeaderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetHeaderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHeaderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHeaderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Btcheader) > 0 {
		i -= len(m.Btcheader)
		copy(dAtA[i:], m.Btcheader)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Btcheader)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLatestBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLatestBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Btclightblock != nil {
		{
			size := m.Btclightblock.Size()
			i -= size
			if _, err := m.Btclightblock.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetHeaderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetHeaderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Btcheader)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLatestBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLatestBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Btclightblock != nil {
		l = m.Btclightblock.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHeaderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHeaderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHeaderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHeaderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHeaderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHeaderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Btcheader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Btcheader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Btclightblock", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v BTCLightBlock
			m.Btclightblock = &v
			if err := m.Btclightblock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
