name: Tests
on:
  pull_request:
    types: [opened, synchronize, labeled]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
          FILES: |
            go.mod
            go.sum
      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "1.23"
          cache: true
      - name: Compile
        if: env.GIT_DIFF
        run: |
          go mod download
          make build

  test-unit-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
          FILES: |
            go.mod
            go.sum
      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "1.23"
          cache: true
      - name: Test and Create Coverage Report
        if: env.GIT_DIFF
        run: |
          EXPERIMENTAL=true make test-unit
      #     EXPERIMENTAL=true make test-unit-cover
      # - uses: codecov/codecov-action@v4.6.0
      #   if: env.GIT_DIFF
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.txt
      #     fail_ci_if_error: true
      #     verbose: true

  # test-e2e:
  #   # skip the e2e tests when `skip-e2e-test` label is present on pull request
  #   if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-e2e-test') }}
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 25
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: technote-space/get-diff-action@v6.1.2
  #       with:
  #         PATTERNS: |
  #           **/**.go
  #         FILES: |
  #           go.mod
  #           go.sum
  #     - uses: actions/setup-go@v5
  #       if: env.GIT_DIFF
  #       with:
  #         go-version: "1.23"
  #         cache: true

  #     - name: Test E2E
  #       if: env.GIT_DIFF
  #       run: |
  #         make test-e2e
